name: Azure Static Web Apps - platanosoftware-redirect

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PLATA_PLATANOSOFTWARE_REDIRECT }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/platanosoftware-redirect"
          api_location: ""
          app_artifact_location: ""